post_app/urls.py
from django.urls import path

from .views import (post_model_create_and_list_view,
                    like_unlike_posts,
                    PostDeleteView,
                    PostUpdateView
                    )

app_name = 'posts'

urlpatterns =[
    path('', post_model_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_posts, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profile_app/urls.py
from django.urls import path
from .views import (my_profile_view,
                    invites_received_view,
                    profiles_list_view,
                    invite_profile_list_view,
                    ProfileListView,
                    send_invatation,
                    remove_from_friends,
                    accept_invatation,
                    reject_invatation,
                    ProfileDetailView,
                    reject_sent_invatation,
                    )

app_name = 'profiles'

urlpatterns = [
    path('my_profile/', my_profile_view, name='my_profile'),
    path('my_invites/', invites_received_view, name='my_invites'),
    path('', ProfileListView.as_view(), name='profile_list'),
    path('to_invite/', invite_profile_list_view, name='invite_profiles'),
    path('send_invite/', send_invatation, name='send_invite'),
    path('remove_friend/', remove_from_friends, name='remove_friend'),
    path('my_invites/accept/', accept_invatation, name='accept_invite'),
    path('my_invites/reject/', reject_invatation, name='reject_invite'),
    path('to_invite/reject/', reject_sent_invatation, name='reject_sent_invatations'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile_detail_view'),
]

soc_net_app/urls.py
from django.urls import path
from soc_net_app.views import MainPaige

urlpatterns = [
    path('home/', MainPaige.as_view(), name='home'),
]

soc_net_project/urls.py
from django.contrib import admin
from django.urls import path, include
from soc_net_project import settings
from django.conf.urls.static import static

from soc_net_app.views import MainPaige

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soc_net_app.urls')),
    path('profile/', include('profile_app.urls', namespace='profiles')),
    path('posts/', include('post_app.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

soc_net_app/models.py
from django.db import models

# Create your models here.

soc_net_app/views.py
from django.shortcuts import render
from django.views import generic



class MainPaige(generic.TemplateView):
    template_name = 'main/home.html'

soc_net_app/templates/main/navbar.html
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'home' as path_to_home %}
{% url 'profiles:my_profile' as path_to_my_profile %}
{% url 'profiles:my_invites' as path_to_my_invites %}
{% url 'profiles:invite_profiles' as path_to_invites %}
{% url 'profiles:profile_list' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>My net</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        <h4>Board</h4>
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Sent Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 <h5>{{ request.user }}</h5>
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                <h5>Logout</h5>
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>