post_app/urls.py
from django.urls import path

from .views import (post_model_create_and_list_view,
                    like_unlike_posts,
                    PostDeleteView,
                    PostUpdateView
                    )

app_name = 'posts'

urlpatterns =[
    path('', post_model_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_posts, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profile_app/urls.py
from django.urls import path
from .views import (my_profile_view,
                    invites_received_view,
                    profiles_list_view,
                    invite_profile_list_view,
                    ProfileListView,
                    send_invatation,
                    remove_from_friends,
                    accept_invatation,
                    reject_invatation,
                    ProfileDetailView,
                    reject_sent_invatation,
                    )

app_name = 'profiles'

urlpatterns = [
    path('my_profile/', my_profile_view, name='my_profile'),
    path('my_invites/', invites_received_view, name='my_invites'),
    path('', ProfileListView.as_view(), name='profile_list'),
    path('to_invite/', invite_profile_list_view, name='invite_profiles'),
    path('send_invite/', send_invatation, name='send_invite'),
    path('remove_friend/', remove_from_friends, name='remove_friend'),
    path('my_invites/accept/', accept_invatation, name='accept_invite'),
    path('my_invites/reject/', reject_invatation, name='reject_invite'),
    path('to_invite/reject/', reject_sent_invatation, name='reject_sent_invatations'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile_detail_view'),
]

soc_net_project/urls.py
from django.contrib import admin
from django.urls import path, include
from soc_net_project import settings
from django.conf.urls.static import static

from soc_net_app.views import MainPaige

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soc_net_app.urls')),
    path('profile/', include('profile_app.urls', namespace='profiles')),
    path('posts/', include('post_app.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profile_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q


class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        accepted = set([])

        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        return available


    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No bio...", max_length=300)
    email = models.EmailField()
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.jpg', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, default=None, null=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username} - {self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse('profiles:profile_detail_view', kwargs={'slug': self.slug})

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + "" + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

    def get_friends(self):
        return self.friends.all()

    def get_friends_count(self):
        return self.friends.all().count()

    def get_posts_count(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_like_given_count(self):
        likes = self.likes_user.all()
        total_like = 0
        for item in likes:
            if item.value == 'Like':
                total_like += 1
        return total_like

    def get_received_like_count(self):
        posts = self.posts.all()
        total_like = 0
        for post in posts:
            total_like += post.likes_post.count()
        return total_like

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted'),
)


class RelationshipManager(models.Manager):
    def invatations_recieved(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs

    def invatations_sent(self, sender):
        qs = Relationship.objects.filter(sender=sender, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender} - {self.receiver} - {self.status}"

profile_app/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

profile_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from profile_app.models import Profile, Relationship
from .forms import ProfileModelForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'profile_app/my_profile.html', context=context)

@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_recieved(receiver=profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'profile_app/my_invites.html', context=context)

@login_required
def accept_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my_invites')

@login_required
def reject_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my_invites')

@login_required
def reject_sent_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(pk=pk)
        sender = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:invite_profiles')

@login_required
def invite_profile_list_view(request):
    user = User.objects.get(username__iexact=request.user)
    profile = Profile.objects.get(user=user)
    qs = Relationship.objects.invatations_sent(sender=profile)
    results = list(map(lambda x: x.receiver, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'qs': results,
        'is_empty': is_empty,
        }

    return render(request, 'profile_app/invite_profiles.html', context=context)
@login_required
def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(me=user)

    context = {
        'qs': qs,
    }

    return render(request, 'profile_app/profiles_list.html', context=context)

class ProfileListView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = 'profile_app/profiles_list.html'
    context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(me=self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_receiver = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        rel_sender = []
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context

@login_required
def send_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my_profile')

@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver) | (Q(sender=receiver) & Q(receiver=sender)))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my_profile')


class ProfileDetailView(LoginRequiredMixin, generic.DeleteView):
    model = Profile
    template_name = 'profile_app/profile_view.html'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_receiver = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        rel_sender = []
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context

profile_app/templates/profile_app/invite_profiles.html
{% extends 'base.html' %}

{% block title %}
Invite profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No invitations here...</h1>
    {% endif %}

    {% for obj in qs %}
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="ui three wide column">
                    <img class="ui small circular image" src={{obj.avatar.url}} alt="">
                </div>
                <div class="ui thirteen wide column">
                     <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>
                        <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        <br>
                        <form action="{% url 'profiles:reject_sent_invatations' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>Reject invite
                            </button>
                        </form>
                </div>
            </div>
        </div>

    </div>
    {% endfor %}


{% endblock content %}

profile_app/templates/profile_app/my_invites.html
{% extends 'base.html' %}

{% block title %}
My invites
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No invitations here...</h1>
    {% endif %}

    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'profiles:accept_invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>Accept invite
                            </button>
                        </form>
                        <form action="{% url 'profiles:reject_invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>Reject invite
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

profile_app/templates/profile_app/my_profile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update your Profile:
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional info about you.</div>
        <form method="POST" class="ui form" enctype="multipart/form-data">
          {% csrf_token %}
          {{form.as_p}}
    </div>
  </div>
  <div class="actions">
    <button type="submit" class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
      </form>
  </div>
</div>
<div class="ui segment">
  {% if confirm %}
    <div class="ui green message">Your profile has been updated!</div>
    <hr>
  {% endif %}
  <h3>{{profile.first_name}} {{profile.last_name}}</h3>
  <div class="ui grid">
    <div class="row">
      <div class="six wide column">
        <img class="ui medium rounded image" src="{{profile.avatar.url}}" alt="">
        <div class="row mt-5">
          <button class="ui secondary button" id="modal-btn">Update your profile</button>
        </div>
      </div>
      <div class="ten wide column">
        <table class="ui table">
          <tbody>
            <tr>
              <td>Username</td>
              <td>{{profile.user}}</td>
            </tr>
            <tr>
              <td>First name</td>
              <td>{{profile.first_name}}</td>
            </tr>
            <tr>
              <td>Last name</td>
              <td>{{profile.last_name}}</td>
            </tr>
            <tr>
              <td>BIO</td>
              <td>{{profile.bio}}</td>
            </tr>
            <tr>
              <td>Country</td>
              <td>{{profile.country}}</td>
            </tr>
            <tr>
              <td>Number of friends</td>
              <td>{{profile.get_friends_count}}</td>
            </tr>
            <tr>
              <td>Friends</td>
              <td>
                <ul>
                  {% for friend in profile.get_friends %}
                  <li><img class="ui small circular image" src={{friend.avatar.url}} alt="">{{friend}}</li>
                  {% endfor %}
                </ul>
              </td>
            </tr>
            <tr>
              <td>Total recieved likes</td>
              <td>{{profile.get_received_like_count}}</td>
            </tr>
            <tr>
              <td>Total posts count</td>
              <td>{{profile.get_posts_count}}</td>
            </tr>
            <tr>
              <td>Total likes given</td>
              <td>{{profile.get_like_given_count}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

profile_app/templates/profile_app/profile_view.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}


{% block content %}
    <div class="ui grid">
        <br>
        <div class="row">
            <div class="four wide column">
                <img class="ui medium rounded image" src={{object.avatar.url}} alt="">
                <h1>{{object.user}}</h1>
                <div class="ui vertical fluid menu">
                    <div class="item">
                        Posts
                        <div class="ui label">
                            {{ object.get_posts_count }}
                        </div>
                    </div>
                    <div class="item">
                        Likes given
                        <div class="ui label">
                            {{ object.get_like_given_count }}
                        </div>
                    </div>
                    <div class="item">
                        Likes received
                        <div class="ui label">
                            {{ object.get_received_like_count }}
                        </div>
                    </div>
                    <div class="item">
                        Friends
                        <div class="ui label">
                            {{ object.get_friends_count }}
                        </div>
                    </div>
                </div>
                {% if object.user not in rel_receiver and object.user not in rel_sender %}
                    <form action="{% url 'profiles:send_invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                    </form>
                {% endif %}
                <br>
                {% if object.user in rel_receiver and request.user not in object.friends.all %}
                    <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                {% endif %}

                {% if request.user in object.friends.all %}
                    <form action="{% url 'profiles:remove_friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                    </form>
                {% endif %}
            </div>
            <div class="twelve wide column">
                {% if len_posts %}
                    {% for post in posts %}
                        <div class="segment ui fluid">
                            {% if post.image %}
                                <img class="ui big image" src={{post.image.url}} alt="">
                            {% endif %}
                            {{ post.content }}
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>No posts here...</h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

profile_app/templates/profile_app/profiles_list.html
{% extends 'base.html' %}

{% block title %}
Profiles list
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}
    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send_invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                        {% endif %}
                        <br>
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                            <form action="{% url 'profiles:remove_friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


{% endblock content %}